### ISSUE TITLE
This Flask quiz is written in and based on Ruby

### ISSUE THREAD

**Issue by a-JAVA-chip-frappuccino** [learn-co-curriculum/python-p4-quiz-retrieving-data-from-apis#1]
### Canvas Link

https://learning.flatironschool.com/courses/6259/quizzes/45206

### Concern

Although this is in the Python/Flask Phase 4 curriculum, the questions are all based on the Ruby on Rails curriculum.

### Suggested Changes

Change to Flask questions.

**Comment by professor-ben** [comment]
You can safely ignore this quiz for the time being. We'll have a new one up with the appropriate questions shortly.

**Comment by pgill97** [comment]
Deprecated
